/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttendanceStatus = { 'Present' : null } |
  { 'Absent' : null };
export type FeeCategory = { 'OTP' : null } |
  { 'Monthly' : null } |
  { 'Term1' : null } |
  { 'Term2' : null } |
  { 'Term3' : null } |
  { 'HalfYearly' : null };
export interface Payment {
  'id' : bigint,
  'studentId' : bigint,
  'amountPaid' : number,
  'paymentDate' : Time,
  'paymentMode' : PaymentMode,
  'feeCategory' : FeeCategory,
}
export type PaymentMode = { 'UPI' : null } |
  { 'Cash' : null } |
  { 'BankTransfer' : null };
export interface ReportCard {
  'studentId' : bigint,
  'subjects' : Array<string>,
  'marksEntries' : Array<Array<number>>,
  'columns' : Array<string>,
}
export interface Student {
  'id' : bigint,
  'payments' : Array<Payment>,
  'discountAmount' : number,
  'name' : string,
  'section' : string,
  'motherName' : string,
  'feePaymentCategory' : FeeCategory,
  'reportCard' : [] | [ReportCard],
  'totalFee' : number,
  'examFeesSA1' : number,
  'examFeesSA2' : number,
  'fatherName' : string,
  'contactNumber' : string,
  'studentClass' : string,
  'finalFee' : number,
}
export type Time = bigint;
export interface TransportMonthlyPayment {
  'id' : bigint,
  'month' : bigint,
  'studentId' : bigint,
  'paid' : boolean,
  'year' : bigint,
}
export type TransportOption = { 'OnlyPickUp' : null } |
  { 'OnlyDrop' : null } |
  { 'PickUpDrop' : null };
export interface TransportStudent {
  'id' : bigint,
  'transportOption' : TransportOption,
  'name' : string,
  'isActive' : boolean,
  'fatherName' : string,
  'contactNumber' : string,
  'monthlyPayments' : Array<TransportMonthlyPayment>,
  'monthlyFee' : number,
}
export interface _SERVICE {
  'addFeePayment' : ActorMethod<
    [bigint, number, Time, PaymentMode, FeeCategory],
    bigint
  >,
  'addStudent' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      FeeCategory,
      number,
      number,
      number,
      number,
    ],
    bigint
  >,
  'addTransportStudent' : ActorMethod<
    [string, string, string, TransportOption, number],
    bigint
  >,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'deleteTransportStudent' : ActorMethod<[bigint], undefined>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getReportCard' : ActorMethod<[bigint], [] | [ReportCard]>,
  'getStudentById' : ActorMethod<[bigint], [] | [Student]>,
  'getUnpaidTransportStudents' : ActorMethod<
    [bigint, bigint],
    Array<TransportStudent>
  >,
  'markTransportFeePaid' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'saveAttendance' : ActorMethod<
    [Time, string, Array<[bigint, string, AttendanceStatus]>],
    undefined
  >,
  'saveOrUpdateReportCard' : ActorMethod<
    [bigint, Array<string>, Array<string>, Array<Array<number>>],
    undefined
  >,
  'updateStudent' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      FeeCategory,
      number,
      number,
      number,
      number,
    ],
    undefined
  >,
  'updateTransportStudent' : ActorMethod<
    [bigint, string, string, string, TransportOption, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];