/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PaymentMode = IDL.Variant({
  'UPI' : IDL.Null,
  'Cash' : IDL.Null,
  'BankTransfer' : IDL.Null,
});
export const FeeCategory = IDL.Variant({
  'OTP' : IDL.Null,
  'Monthly' : IDL.Null,
  'Term1' : IDL.Null,
  'Term2' : IDL.Null,
  'Term3' : IDL.Null,
  'HalfYearly' : IDL.Null,
});
export const TransportOption = IDL.Variant({
  'OnlyPickUp' : IDL.Null,
  'OnlyDrop' : IDL.Null,
  'PickUpDrop' : IDL.Null,
});
export const StudentExtras = IDL.Record({
  'studentId' : IDL.Nat,
  'dateOfBirth' : IDL.Text,
  'aadharNo' : IDL.Text,
  'admissionNo' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'amountPaid' : IDL.Float64,
  'paymentDate' : Time,
  'paymentMode' : PaymentMode,
  'feeCategory' : FeeCategory,
});
export const ReportCard = IDL.Record({
  'studentId' : IDL.Nat,
  'subjects' : IDL.Vec(IDL.Text),
  'marksEntries' : IDL.Vec(IDL.Vec(IDL.Float64)),
  'columns' : IDL.Vec(IDL.Text),
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'payments' : IDL.Vec(Payment),
  'discountAmount' : IDL.Float64,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'motherName' : IDL.Text,
  'feePaymentCategory' : FeeCategory,
  'reportCard' : IDL.Opt(ReportCard),
  'totalFee' : IDL.Float64,
  'examFeesSA1' : IDL.Float64,
  'examFeesSA2' : IDL.Float64,
  'fatherName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'studentClass' : IDL.Text,
  'finalFee' : IDL.Float64,
});
export const TransportMonthlyPayment = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'studentId' : IDL.Nat,
  'paid' : IDL.Bool,
  'year' : IDL.Nat,
});
export const TransportStudent = IDL.Record({
  'id' : IDL.Nat,
  'transportOption' : TransportOption,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'fatherName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'monthlyPayments' : IDL.Vec(TransportMonthlyPayment),
  'monthlyFee' : IDL.Float64,
});
export const AttendanceStatus = IDL.Variant({
  'Present' : IDL.Null,
  'Absent' : IDL.Null,
});

export const idlService = IDL.Service({
  'addFeePayment' : IDL.Func(
      [IDL.Nat, IDL.Float64, Time, PaymentMode, FeeCategory],
      [IDL.Nat],
      [],
    ),
  'addStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        FeeCategory,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'addTransportStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TransportOption, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteTransportStudent' : IDL.Func([IDL.Nat], [], []),
  'getAllStudentExtras' : IDL.Func([], [IDL.Vec(StudentExtras)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getReportCard' : IDL.Func([IDL.Nat], [IDL.Opt(ReportCard)], ['query']),
  'getStudentById' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudentExtras' : IDL.Func([IDL.Nat], [IDL.Opt(StudentExtras)], ['query']),
  'getUnpaidTransportStudents' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(TransportStudent)],
      ['query'],
    ),
  'markTransportFeePaid' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'saveAttendance' : IDL.Func(
      [Time, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, AttendanceStatus))],
      [],
      [],
    ),
  'saveOrUpdateReportCard' : IDL.Func(
      [
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Vec(IDL.Float64)),
      ],
      [],
      [],
    ),
  'setStudentExtras' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateStudent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        FeeCategory,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'updateTransportStudent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, TransportOption, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PaymentMode = IDL.Variant({
    'UPI' : IDL.Null,
    'Cash' : IDL.Null,
    'BankTransfer' : IDL.Null,
  });
  const FeeCategory = IDL.Variant({
    'OTP' : IDL.Null,
    'Monthly' : IDL.Null,
    'Term1' : IDL.Null,
    'Term2' : IDL.Null,
    'Term3' : IDL.Null,
    'HalfYearly' : IDL.Null,
  });
  const TransportOption = IDL.Variant({
    'OnlyPickUp' : IDL.Null,
    'OnlyDrop' : IDL.Null,
    'PickUpDrop' : IDL.Null,
  });
  const StudentExtras = IDL.Record({
    'studentId' : IDL.Nat,
    'dateOfBirth' : IDL.Text,
    'aadharNo' : IDL.Text,
    'admissionNo' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'amountPaid' : IDL.Float64,
    'paymentDate' : Time,
    'paymentMode' : PaymentMode,
    'feeCategory' : FeeCategory,
  });
  const ReportCard = IDL.Record({
    'studentId' : IDL.Nat,
    'subjects' : IDL.Vec(IDL.Text),
    'marksEntries' : IDL.Vec(IDL.Vec(IDL.Float64)),
    'columns' : IDL.Vec(IDL.Text),
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'payments' : IDL.Vec(Payment),
    'discountAmount' : IDL.Float64,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'motherName' : IDL.Text,
    'feePaymentCategory' : FeeCategory,
    'reportCard' : IDL.Opt(ReportCard),
    'totalFee' : IDL.Float64,
    'examFeesSA1' : IDL.Float64,
    'examFeesSA2' : IDL.Float64,
    'fatherName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'studentClass' : IDL.Text,
    'finalFee' : IDL.Float64,
  });
  const TransportMonthlyPayment = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'studentId' : IDL.Nat,
    'paid' : IDL.Bool,
    'year' : IDL.Nat,
  });
  const TransportStudent = IDL.Record({
    'id' : IDL.Nat,
    'transportOption' : TransportOption,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'fatherName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'monthlyPayments' : IDL.Vec(TransportMonthlyPayment),
    'monthlyFee' : IDL.Float64,
  });
  const AttendanceStatus = IDL.Variant({
    'Present' : IDL.Null,
    'Absent' : IDL.Null,
  });
  
  return IDL.Service({
    'addFeePayment' : IDL.Func(
        [IDL.Nat, IDL.Float64, Time, PaymentMode, FeeCategory],
        [IDL.Nat],
        [],
      ),
    'addStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          FeeCategory,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'addTransportStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TransportOption, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteTransportStudent' : IDL.Func([IDL.Nat], [], []),
    'getAllStudentExtras' : IDL.Func([], [IDL.Vec(StudentExtras)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getReportCard' : IDL.Func([IDL.Nat], [IDL.Opt(ReportCard)], ['query']),
    'getStudentById' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudentExtras' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StudentExtras)],
        ['query'],
      ),
    'getUnpaidTransportStudents' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(TransportStudent)],
        ['query'],
      ),
    'markTransportFeePaid' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'saveAttendance' : IDL.Func(
        [
          Time,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, AttendanceStatus)),
        ],
        [],
        [],
      ),
    'saveOrUpdateReportCard' : IDL.Func(
        [
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Vec(IDL.Float64)),
        ],
        [],
        [],
      ),
    'setStudentExtras' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateStudent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          FeeCategory,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'updateTransportStudent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, TransportOption, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };