/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudentExtras {
    studentId: bigint;
    dateOfBirth: string;
    aadharNo: string;
    admissionNo: string;
}
export interface TransportMonthlyPayment {
    id: bigint;
    month: bigint;
    studentId: bigint;
    paid: boolean;
    year: bigint;
}
export type Time = bigint;
export interface TransportStudent {
    id: bigint;
    transportOption: TransportOption;
    name: string;
    isActive: boolean;
    fatherName: string;
    contactNumber: string;
    monthlyPayments: Array<TransportMonthlyPayment>;
    monthlyFee: number;
}
export interface ReportCard {
    studentId: bigint;
    subjects: Array<string>;
    marksEntries: Array<Array<number>>;
    columns: Array<string>;
}
export interface Payment {
    id: bigint;
    studentId: bigint;
    amountPaid: number;
    paymentDate: Time;
    paymentMode: PaymentMode;
    feeCategory: FeeCategory;
}
export interface Student {
    id: bigint;
    payments: Array<Payment>;
    discountAmount: number;
    name: string;
    section: string;
    motherName: string;
    feePaymentCategory: FeeCategory;
    reportCard?: ReportCard;
    totalFee: number;
    examFeesSA1: number;
    examFeesSA2: number;
    fatherName: string;
    contactNumber: string;
    studentClass: string;
    finalFee: number;
}
export enum AttendanceStatus {
    Present = "Present",
    Absent = "Absent"
}
export enum FeeCategory {
    OTP = "OTP",
    Monthly = "Monthly",
    Term1 = "Term1",
    Term2 = "Term2",
    Term3 = "Term3",
    HalfYearly = "HalfYearly"
}
export enum PaymentMode {
    UPI = "UPI",
    Cash = "Cash",
    BankTransfer = "BankTransfer"
}
export enum TransportOption {
    OnlyPickUp = "OnlyPickUp",
    OnlyDrop = "OnlyDrop",
    PickUpDrop = "PickUpDrop"
}
export interface backendInterface {
    addFeePayment(studentId: bigint, amountPaid: number, paymentDate: Time, paymentMode: PaymentMode, feeCategory: FeeCategory): Promise<bigint>;
    addStudent(name: string, studentClass: string, section: string, fatherName: string, motherName: string, contactNumber: string, totalFee: number, feePaymentCategory: FeeCategory, discountAmount: number, finalFee: number, examFeesSA1: number, examFeesSA2: number): Promise<bigint>;
    addTransportStudent(name: string, fatherName: string, contactNumber: string, transportOption: TransportOption, monthlyFee: number): Promise<bigint>;
    deleteStudent(id: bigint): Promise<void>;
    deleteTransportStudent(id: bigint): Promise<void>;
    getAllStudentExtras(): Promise<Array<StudentExtras>>;
    getAllStudents(): Promise<Array<Student>>;
    getReportCard(studentId: bigint): Promise<ReportCard | null>;
    getStudentById(id: bigint): Promise<Student | null>;
    getStudentExtras(studentId: bigint): Promise<StudentExtras | null>;
    getUnpaidTransportStudents(month: bigint, year: bigint): Promise<Array<TransportStudent>>;
    markTransportFeePaid(studentId: bigint, month: bigint, year: bigint): Promise<void>;
    saveAttendance(date: Time, classSection: string, records: Array<[bigint, string, AttendanceStatus]>): Promise<void>;
    saveOrUpdateReportCard(studentId: bigint, subjects: Array<string>, columns: Array<string>, marksEntries: Array<Array<number>>): Promise<void>;
    setStudentExtras(studentId: bigint, dateOfBirth: string, aadharNo: string, admissionNo: string): Promise<void>;
    updateStudent(id: bigint, name: string, studentClass: string, section: string, fatherName: string, motherName: string, contactNumber: string, totalFee: number, feePaymentCategory: FeeCategory, discountAmount: number, finalFee: number, examFeesSA1: number, examFeesSA2: number): Promise<void>;
    updateTransportStudent(id: bigint, name: string, fatherName: string, contactNumber: string, transportOption: TransportOption, monthlyFee: number): Promise<void>;
}
import type { AttendanceStatus as _AttendanceStatus, FeeCategory as _FeeCategory, Payment as _Payment, PaymentMode as _PaymentMode, ReportCard as _ReportCard, Student as _Student, StudentExtras as _StudentExtras, Time as _Time, TransportMonthlyPayment as _TransportMonthlyPayment, TransportOption as _TransportOption, TransportStudent as _TransportStudent } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFeePayment(arg0: bigint, arg1: number, arg2: Time, arg3: PaymentMode, arg4: FeeCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeePayment(arg0, arg1, arg2, to_candid_PaymentMode_n1(this._uploadFile, this._downloadFile, arg3), to_candid_FeeCategory_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeePayment(arg0, arg1, arg2, to_candid_PaymentMode_n1(this._uploadFile, this._downloadFile, arg3), to_candid_FeeCategory_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: number, arg7: FeeCategory, arg8: number, arg9: number, arg10: number, arg11: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_FeeCategory_n3(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_FeeCategory_n3(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async addTransportStudent(arg0: string, arg1: string, arg2: string, arg3: TransportOption, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransportStudent(arg0, arg1, arg2, to_candid_TransportOption_n5(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransportStudent(arg0, arg1, arg2, to_candid_TransportOption_n5(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deleteStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTransportStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransportStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransportStudent(arg0);
            return result;
        }
    }
    async getAllStudentExtras(): Promise<Array<StudentExtras>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentExtras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentExtras();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportCard(arg0: bigint): Promise<ReportCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCard(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCard(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentById(arg0: bigint): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentExtras(arg0: bigint): Promise<StudentExtras | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentExtras(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentExtras(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnpaidTransportStudents(arg0: bigint, arg1: bigint): Promise<Array<TransportStudent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnpaidTransportStudents(arg0, arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnpaidTransportStudents(arg0, arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async markTransportFeePaid(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTransportFeePaid(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTransportFeePaid(arg0, arg1, arg2);
            return result;
        }
    }
    async saveAttendance(arg0: Time, arg1: string, arg2: Array<[bigint, string, AttendanceStatus]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAttendance(arg0, arg1, to_candid_vec_n25(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAttendance(arg0, arg1, to_candid_vec_n25(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveOrUpdateReportCard(arg0: bigint, arg1: Array<string>, arg2: Array<string>, arg3: Array<Array<number>>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOrUpdateReportCard(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOrUpdateReportCard(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setStudentExtras(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStudentExtras(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStudentExtras(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateStudent(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: number, arg8: FeeCategory, arg9: number, arg10: number, arg11: number, arg12: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_FeeCategory_n3(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_FeeCategory_n3(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12);
            return result;
        }
    }
    async updateTransportStudent(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: TransportOption, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransportStudent(arg0, arg1, arg2, arg3, to_candid_TransportOption_n5(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransportStudent(arg0, arg1, arg2, arg3, to_candid_TransportOption_n5(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
}
function from_candid_FeeCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeCategory): FeeCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TransportOption_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransportOption): TransportOption {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TransportStudent_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransportStudent): TransportStudent {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportCard]): ReportCard | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentExtras]): StudentExtras | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    studentId: bigint;
    amountPaid: number;
    paymentDate: _Time;
    paymentMode: _PaymentMode;
    feeCategory: _FeeCategory;
}): {
    id: bigint;
    studentId: bigint;
    amountPaid: number;
    paymentDate: Time;
    paymentMode: PaymentMode;
    feeCategory: FeeCategory;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        amountPaid: value.amountPaid,
        paymentDate: value.paymentDate,
        paymentMode: from_candid_PaymentMode_n13(_uploadFile, _downloadFile, value.paymentMode),
        feeCategory: from_candid_FeeCategory_n15(_uploadFile, _downloadFile, value.feeCategory)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transportOption: _TransportOption;
    name: string;
    isActive: boolean;
    fatherName: string;
    contactNumber: string;
    monthlyPayments: Array<_TransportMonthlyPayment>;
    monthlyFee: number;
}): {
    id: bigint;
    transportOption: TransportOption;
    name: string;
    isActive: boolean;
    fatherName: string;
    contactNumber: string;
    monthlyPayments: Array<TransportMonthlyPayment>;
    monthlyFee: number;
} {
    return {
        id: value.id,
        transportOption: from_candid_TransportOption_n23(_uploadFile, _downloadFile, value.transportOption),
        name: value.name,
        isActive: value.isActive,
        fatherName: value.fatherName,
        contactNumber: value.contactNumber,
        monthlyPayments: value.monthlyPayments,
        monthlyFee: value.monthlyFee
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    payments: Array<_Payment>;
    discountAmount: number;
    name: string;
    section: string;
    motherName: string;
    feePaymentCategory: _FeeCategory;
    reportCard: [] | [_ReportCard];
    totalFee: number;
    examFeesSA1: number;
    examFeesSA2: number;
    fatherName: string;
    contactNumber: string;
    studentClass: string;
    finalFee: number;
}): {
    id: bigint;
    payments: Array<Payment>;
    discountAmount: number;
    name: string;
    section: string;
    motherName: string;
    feePaymentCategory: FeeCategory;
    reportCard?: ReportCard;
    totalFee: number;
    examFeesSA1: number;
    examFeesSA2: number;
    fatherName: string;
    contactNumber: string;
    studentClass: string;
    finalFee: number;
} {
    return {
        id: value.id,
        payments: from_candid_vec_n10(_uploadFile, _downloadFile, value.payments),
        discountAmount: value.discountAmount,
        name: value.name,
        section: value.section,
        motherName: value.motherName,
        feePaymentCategory: from_candid_FeeCategory_n15(_uploadFile, _downloadFile, value.feePaymentCategory),
        reportCard: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.reportCard)),
        totalFee: value.totalFee,
        examFeesSA1: value.examFeesSA1,
        examFeesSA2: value.examFeesSA2,
        fatherName: value.fatherName,
        contactNumber: value.contactNumber,
        studentClass: value.studentClass,
        finalFee: value.finalFee
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Cash: null;
} | {
    BankTransfer: null;
}): PaymentMode {
    return "UPI" in value ? PaymentMode.UPI : "Cash" in value ? PaymentMode.Cash : "BankTransfer" in value ? PaymentMode.BankTransfer : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OTP: null;
} | {
    Monthly: null;
} | {
    Term1: null;
} | {
    Term2: null;
} | {
    Term3: null;
} | {
    HalfYearly: null;
}): FeeCategory {
    return "OTP" in value ? FeeCategory.OTP : "Monthly" in value ? FeeCategory.Monthly : "Term1" in value ? FeeCategory.Term1 : "Term2" in value ? FeeCategory.Term2 : "Term3" in value ? FeeCategory.Term3 : "HalfYearly" in value ? FeeCategory.HalfYearly : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnlyPickUp: null;
} | {
    OnlyDrop: null;
} | {
    PickUpDrop: null;
}): TransportOption {
    return "OnlyPickUp" in value ? TransportOption.OnlyPickUp : "OnlyDrop" in value ? TransportOption.OnlyDrop : "PickUpDrop" in value ? TransportOption.PickUpDrop : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransportStudent>): Array<TransportStudent> {
    return value.map((x)=>from_candid_TransportStudent_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_FeeCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeCategory): _FeeCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TransportOption_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransportOption): _TransportOption {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_tuple_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, string, AttendanceStatus]): [bigint, string, _AttendanceStatus] {
    return [
        value[0],
        value[1],
        to_candid_AttendanceStatus_n27(_uploadFile, _downloadFile, value[2])
    ];
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    UPI: null;
} | {
    Cash: null;
} | {
    BankTransfer: null;
} {
    return value == PaymentMode.UPI ? {
        UPI: null
    } : value == PaymentMode.Cash ? {
        Cash: null
    } : value == PaymentMode.BankTransfer ? {
        BankTransfer: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    Present: null;
} | {
    Absent: null;
} {
    return value == AttendanceStatus.Present ? {
        Present: null
    } : value == AttendanceStatus.Absent ? {
        Absent: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeCategory): {
    OTP: null;
} | {
    Monthly: null;
} | {
    Term1: null;
} | {
    Term2: null;
} | {
    Term3: null;
} | {
    HalfYearly: null;
} {
    return value == FeeCategory.OTP ? {
        OTP: null
    } : value == FeeCategory.Monthly ? {
        Monthly: null
    } : value == FeeCategory.Term1 ? {
        Term1: null
    } : value == FeeCategory.Term2 ? {
        Term2: null
    } : value == FeeCategory.Term3 ? {
        Term3: null
    } : value == FeeCategory.HalfYearly ? {
        HalfYearly: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransportOption): {
    OnlyPickUp: null;
} | {
    OnlyDrop: null;
} | {
    PickUpDrop: null;
} {
    return value == TransportOption.OnlyPickUp ? {
        OnlyPickUp: null
    } : value == TransportOption.OnlyDrop ? {
        OnlyDrop: null
    } : value == TransportOption.PickUpDrop ? {
        PickUpDrop: null
    } : value;
}
function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, string, AttendanceStatus]>): Array<[bigint, string, _AttendanceStatus]> {
    return value.map((x)=>to_candid_tuple_n26(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
